export enum PIICategory {
  name = "name",
  homeAddress = "homeAddress",
  workAddress = "workAddress",
  phone = "phone",
  fax = "fax",
  email = "email",
  whatsapp = "whatsapp",
  facebook = "facebook",
  instagram = "instagram",
  creditCard = "creditCard",
  race = "race",
  ethnicity = "ethnicity",
  gender = "gender",
  birthGender = "birthGender",
  sexualOrientation = "sexualOrientation",
  birthday = "birthday",
  birthPlace = "birthPlace",
  idNumber = "idNumber",
  ipAddress = "ipAddress"
}